server:
  port: 8085
  servlet:
    context-path: /info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_db
    username: abir
    password: 3323
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true 
